import { Project, Skill, SkillCategory } from "@/types";

export const projects: Project[] = [
  {
    id: "1",
    title: "PingPong Video Messaging",
    description: "An internal office application (Web & Mobile) designed to support employee operational workflows and real-time activity tracking. Developed and maintained backend services to ensure stable data processing and live synchronization across platforms.",
    techStack: ["Laravel", "Next.js", "TypeScript", "PHP", "PostgreSQL"],
    githubUrl: "",
    liveUrl: "https://pingpong.pro",
    featured: true,
  },
  {
    id: "2",
    title: "CS-Ninja",
    description: "A custom-built internal customer support platform designed to replace Zendesk and reduce third-party dependency. Developed as a fullstack web application to manage ticket handling, inquiry tracking, and administrative workflows, improving system control and operational flexibility.",
    techStack: ["Next.js", "TypeScript", "Prisma", "Redis", "PostgreSQL"],
    githubUrl: "",
    liveUrl: "",
    featured: false,
  },
  {
    id: "3",
    title: "CannDr",
    description: "An e-commerce platform (Web & Mobile) that enables users to browse and purchase products online. Contributed to backend API development using Laravel and built the admin dashboard to manage products, orders, and user activities.",
    techStack: ["Laravel", "Laravel Livewire", "Next.js", "MySQL"],
    githubUrl: "",
    liveUrl: "https://canndr.com/",
    featured: true,
  },
  {
    id: "4",
    title: "Social Wifi",
    description: "A web-based platform designed to collect user data through a captive portal for marketing and audience engagement purposes. The system enables customizable captive portal pages and centralized user data management for internal teams. Contributed as a Fullstack Developer, handling backend API development, database design, frontend implementation, and captive portal integration.",
    techStack: ["Laravel", "React.js", "PHP", "JavaScript", "Unifi", "OpenNds", "Mailchimp"],
    githubUrl: "",
    liveUrl: "",
    featured: false,
  },
  {
    id: "5",
    title: "Indolab",
    description: "A multi-platform healthcare application enabling doctor appointment booking, laboratory test ordering, and medicine purchasing. Responsible for backend API development using Express.js, handling core medical service workflows and transactional logic. Designed MongoDB data structures and deployed services using AWS.",
    techStack: ["Express.Js", "Next.js", "TypeScript", "MongoDB", "AWS"],
    githubUrl: "",
    liveUrl: "https://indolab.com",
    featured: false,
  },
  {
    id: "6",
    title: "Climate Budget Tagging (CBT)",
    description: "A financial classification system designed to manage and categorize budget allocations for climate-related programs. Developed scalable backend APIs and integrated responsive frontend features.",
    techStack: ["Laravel", "React.Js", "PHP", "JavaScript", "PostgreSQL"],
    githubUrl: "",
    liveUrl: "https://connect.kemenkeu.go.id/beranda/",
    featured: false,
  },
  {
    id: "7",
    title: "Seeds",
    description: "A web-based investment and trading learning platform that enables users to explore investment opportunities, access educational content, and engage in a community-driven discussion space. Contributed as a Frontend Developer, building responsive and interactive user interfaces to support financial learning and community interaction features.",
    techStack: ["Next.Js", "Golang", "TypeScript", "PostgreSQL"],
    githubUrl: "",
    liveUrl: "https://seeds.finance/",
    featured: false,
  },
];

export const skillCategories: SkillCategory[] = [
  {
    name: "Frontend",
    icon: "Monitor",
    color: "from-cyan-400 to-sky-500",
    skills: [
      { name: "Next.js", level: 95 },
      { name: "React.js", level: 93 },
      { name: "Tailwind CSS", level: 92 },
      { name: "TypeScript", level: 90 },
      { name: "Framer Motion", level: 80 },
      { name: "Laravel Livewire", level: 80 },
    ],
  },
  {
    name: "Backend",
    icon: "Server",
    color: "from-violet-400 to-purple-600",
    skills: [
      { name: "Laravel", level: 95 },
      { name: "Node.js", level: 85 },
      { name: "Express.js", level: 85 },
      { name: "PHP", level: 92 },
      { name: "REST API", level: 95 },
      { name: "Microservices", level: 80 },
    ],
  },
  {
    name: "Database",
    icon: "Database",
    color: "from-emerald-400 to-teal-600",
    skills: [
      { name: "PostgreSQL", level: 80 },
      { name: "MySQL", level: 88 },
      { name: "Redis", level: 82 },
      { name: "Prisma ORM", level: 85 },
      { name: "Eloquent", level: 95 },
    ],
  },
  {
    name: "DevOps",
    icon: "Cloud",
    color: "from-cyan-400 to-sky-500",
    skills: [
      { name: "Docker", level: 65 },
      { name: "GitHub Actions", level: 60 },
      { name: "Nginx", level: 75 },
      { name: "Linux (Ubuntu)", level: 65 },
      { name: "CI/CD Pipelines", level: 55 },
    ],
  },
];
